= Sensor Logging
Lasse Schlör

This readme file needs to be updated. I am leaving this text here as a
placeholder instead of the previous out-of-date text.
// TODO

== Setup

To build:
[source, sh]
----
mkdir build && cd build

# Ninja build system is not needed, just omit the option to use GNU Make.
# Change `Debug` to desired build type or omit for `Release`.
cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug && cd..

# Clearing screen helps while developing but is of course not necessary.
clear && ninja -C build
----

Make sure the following folders exist:
[source, sh]
----
mkdir -p data/shortly data/daily logs/daily
----

Sensors that use the serial port need it to be enabled and the serial console to
be disabled. This can be done with `sudo raspi-config`. If nothing else helps,
disable the `serial-getty` service:
[source, sh]
----
# Example for `/dev/serial0`
sudo systemctl stop serial-getty@serial0.service
sudo systemctl disable serial-getty@serial0.service
----

Configuration is done via source code editing and recompiling, specifically in
the following places:
* a section of `namespace cc` in `src/main.cpp`
* the overloaded function `control_tick` in `src/control.cpp`
* `script/control-structs.json`

To allow the `pi` user to run processes with higher than normal priority (if
desired), a configuration file can be installed as follows. A reboot may be
required for it to take effect.
[source, sh]
----
sudo cp aux/90-pi-priority.conf /etc/security/limits.d/
----

Sample `crontab` entries:
----
13,28,43,58 * * * * nice -n -15 /home/pi/sensor-logging/build/sensor-logging --base-path=/home/pi/sensor-logging shortly
30 4 * * * /home/pi/sensor-logging/build/sensor-logging --base-path=/home/pi/sensor-logging daily
----

== To-do list

* TODO: Think about safety and robustness in terms of power outages
* TODO: Write a script (probably Python) that can take time ranges and column
  names as inputs, then reads relevant shortly files (in CSV format, maybe
  additionally TOML) and daily archives, and outputs the selected subset of data
  (probably as CSV, maybe additionally TOML).
* TODO: Write a small web server that shows a plot of the latest data?
* TODO: Other to-do marks in the code
