import os
import json
import textwrap

def indent(str, n = 1, predicate = None):
  return textwrap.indent(str, "  " * n, predicate)

def control_cpp_include(control_structs):
  str = f''
  sep = f'\n'

  rel_file_path = os.path.relpath(__file__,
    os.path.join(os.path.dirname(__file__), "..", "src"))
  str += f'// File generated by `{rel_file_path}`\n' + sep

  # str += snippet_…() + sep

  # for snippet in [snippet_…]:
  #   for sensor_name, sensor_params in sensors.items():
  #     str += indent(snippet(sensor_name, sensor_params) + sep)

  # str += snippet_…() + sep

  return str

control_structs_json_filename = os.path.join(os.path.dirname(__file__),
  "control-structs.json")
control_cpp_filename = os.path.join(os.path.dirname(__file__), "..", "src",
  "control.generated.cpp")

with open(control_structs_json_filename, "r") as f:
  control_structs = json.load(f)

control_cpp_include_str = control_cpp_include(control_structs)

with open(control_cpp_filename, "w") as f:
  f.write(control_cpp_include_str)

