import os
import socket
import textwrap
import time

def indent(str, n = 1):
  return textwrap.indent(str, "  " * n)

def machine_include():
  str = f''
  sep = f'\n'

  rel_file_path = os.path.relpath(__file__,
    os.path.join(os.path.dirname(__file__), "..", "src"))
  str += f'// File generated by `{rel_file_path}`\n' + sep

  includes = []

  for include in includes:
    str += f'#include <{include}>\n'
    pass

  str += sep + f'namespace cc {{\n' + sep

  str += indent(f'std::string_view constexpr ' +
    f'hostname{{"{socket.gethostname()}"}};\n' + sep)

  return str + f'}} // namespace cc\n'

machine_cpp_filename = os.path.join(os.path.dirname(__file__), "..", "src",
  "machine.cpp")
machine_include_str = machine_include()

with open(machine_cpp_filename, "w") as f:
  f.write(machine_include_str)

# print(machine_include_str, end = "")
